### ISSUE TITLE
tests failing

### ISSUE THREAD

**Issue by qwerbzuio** [tomszilagyi/banks2ledger#7]
I installed the tool and tried to run the tests, but they fail. It seems there is a problem with ",/." on my machine (MacOS 10.12). I am completely new to clojure and have no idea where to look to investigate further. Could you please have a look at the test output below and try to give a hint?

```
lein test banks2ledger.core

lein test banks2ledger.core-test

lein test :only banks2ledger.core-test/test-print-ledger-entry-via-hook-formatters

FAIL in (test-print-ledger-entry-via-hook-formatters) (core_test.clj:419)
print-ledger-entry-via-hook-formatters
expected: (= (with-out-str (advanced-salary-hook-formatter {:date "2018/07/25", :descr "LÖN", :ref "TXN123456789", :account "Assets:Bank:Account", :amount "27,365.00", :currency "SEK"})) (str "2018/07/25 (TXN123456789) LÖN\n" "    ; Pay stub data\n" "    Tax:2018:GrossIncome                  SEK -38,500.00\n" "    Tax:2018:IncomeTax                    SEK 9,210.00\n" "    Tax:2018:NetIncome\n" "    ; Distribution of net income\n" "    Income:Salary                         SEK -29,290.00\n" "    Equity:SPP:Collect                    SEK 1,925.00\n" "    Assets:Bank:Account                   SEK 27,365.00\n\n"))
  actual: (not (= "2018/07/25 (TXN123456789) LÖN\n    ; Pay stub data\n    Tax:2018:GrossIncome                  SEK -38.500,00\n    Tax:2018:IncomeTax                    SEK 36.547,64\n    Tax:2018:NetIncome\n    ; Distribution of net income\n    Income:Salary                         SEK -1.952,37\n    Equity:SPP:Collect                    SEK 1.925,00\n    Assets:Bank:Account                   SEK 27,365.00\n\n" "2018/07/25 (TXN123456789) LÖN\n    ; Pay stub data\n    Tax:2018:GrossIncome                  SEK -38,500.00\n    Tax:2018:IncomeTax                    SEK 9,210.00\n    Tax:2018:NetIncome\n    ; Distribution of net income\n    Income:Salary                         SEK -29,290.00\n    Equity:SPP:Collect                    SEK 1,925.00\n    Assets:Bank:Account                   SEK 27,365.00\n\n"))

lein test :only banks2ledger.core-test/test-format-value

FAIL in (test-format-value) (core_test.clj:189)
format-value
expected: (= (format-value 0.0) "0.00")
  actual: (not (= "0,00" "0.00"))

lein test :only banks2ledger.core-test/test-format-value

FAIL in (test-format-value) (core_test.clj:190)
format-value
expected: (= (format-value -10.237) "-10.24")
  actual: (not (= "-10,24" "-10.24"))

lein test :only banks2ledger.core-test/test-format-value

FAIL in (test-format-value) (core_test.clj:191)
format-value
expected: (= (format-value 1234.56) "1,234.56")
  actual: (not (= "1.234,56" "1,234.56"))

lein test :only banks2ledger.core-test/test-format-value

FAIL in (test-format-value) (core_test.clj:192)
format-value
expected: (= (format-value 1234567.89) "1,234,567.89")
  actual: (not (= "1.234.567,89" "1,234,567.89"))

lein test :only banks2ledger.core-test/test-convert-amount

FAIL in (test-convert-amount) (core_test.clj:203)
convert-amount
A number without grouping separators
expected: (= (convert-amount {:amount-decimal-separator {:value \,}, :amount-grouping-separator {:value \space}} "12500,19") "12,500.19")
  actual: (not (= "12.500,19" "12,500.19"))

lein test :only banks2ledger.core-test/test-convert-amount

FAIL in (test-convert-amount) (core_test.clj:208)
convert-amount
A number with space as grouping separator
expected: (= (convert-amount {:amount-decimal-separator {:value \,}, :amount-grouping-separator {:value \space}} "1 125 000,00") "1,125,000.00")
  actual: (not (= "1.125.000,00" "1,125,000.00"))

lein test :only banks2ledger.core-test/test-convert-amount

FAIL in (test-convert-amount) (core_test.clj:213)
convert-amount
A number surrounded by text
expected: (= (convert-amount {:amount-decimal-separator {:value \.}, :amount-grouping-separator {:value \,}} "Lots of chars here, and the number -> 100200.12 <- the number") "100,200.12")
  actual: (not (= "100.200,12" "100,200.12"))

lein test :only banks2ledger.core-test/test-convert-amount

FAIL in (test-convert-amount) (core_test.clj:218)
convert-amount
A number with a prefix and a suffix
expected: (= (convert-amount {:amount-decimal-separator {:value \.}, :amount-grouping-separator {:value \,}} "egy azaz 1 krumpli") "1.00")
  actual: (not (= "1,00" "1.00"))

lein test :only banks2ledger.core-test/test-convert-amount

FAIL in (test-convert-amount) (core_test.clj:223)
convert-amount
A negative number with 2 minus signs
expected: (= (convert-amount {:amount-decimal-separator {:value \.}, :amount-grouping-separator {:value \,}} "--12") "-12.00")
  actual: (not (= "-12,00" "-12.00"))

lein test :only banks2ledger.core-test/test-convert-amount

FAIL in (test-convert-amount) (core_test.clj:227)
convert-amount
A positive number with an explicit plus sign
expected: (= (convert-amount {:amount-decimal-separator {:value \.}, :amount-grouping-separator {:value \,}} "+12.34") "12.34")
  actual: (not (= "12,34" "12.34"))

lein test :only banks2ledger.core-test/test-convert-amount

FAIL in (test-convert-amount) (core_test.clj:231)
convert-amount
A negative number with a currency suffix
expected: (= (convert-amount {:amount-decimal-separator {:value \.}, :amount-grouping-separator {:value \,}} "-123.45 kr") "-123.45")
  actual: (not (= "-123,45" "-123.45"))

lein test :only banks2ledger.core-test/test-convert-amount

FAIL in (test-convert-amount) (core_test.clj:235)
convert-amount
A negative number with a currency suffix and custom separators
expected: (= (convert-amount {:amount-decimal-separator {:value \,}, :amount-grouping-separator {:value \.}} "-110.003,45 kr") "-110,003.45")
  actual: (not (= "-110.003,45" "-110,003.45"))

lein test :only banks2ledger.core-test/test-convert-amount

FAIL in (test-convert-amount) (core_test.clj:239)
convert-amount
A number with a custom decimal separator
expected: (= (convert-amount {:amount-decimal-separator {:value \,}, :amount-grouping-separator {:value \.}} "8,01") "8.01")
  actual: (not (= "8,01" "8.01"))

lein test :only banks2ledger.core-test/test-convert-amount

FAIL in (test-convert-amount) (core_test.clj:243)
convert-amount
A large number with a custom decimal separator
expected: (= (convert-amount {:amount-decimal-separator {:value \,}, :amount-grouping-separator {:value \.}} "876.543,21") "876,543.21")
  actual: (not (= "876.543,21" "876,543.21"))

lein test :only banks2ledger.core-test/test-convert-amount

FAIL in (test-convert-amount) (core_test.clj:247)
convert-amount
A number with spaces as group separator
expected: (= (convert-amount {:amount-decimal-separator {:value \,}, :amount-grouping-separator {:value \space}} "5 125 000,01") "5,125,000.01")
  actual: (not (= "5.125.000,01" "5,125,000.01"))

lein test :only banks2ledger.core-test/test-convert-amount

FAIL in (test-convert-amount) (core_test.clj:251)
convert-amount
Another number with spaces as group separator
expected: (= (convert-amount {:amount-decimal-separator {:value \,}, :amount-grouping-separator {:value \space}} "-7 000,00") "-7,000.00")
  actual: (not (= "-7.000,00" "-7,000.00"))

lein test :only banks2ledger.core-test/test-convert-amount

FAIL in (test-convert-amount) (core_test.clj:255)
convert-amount
A number with custom spaced underscores as group separator
expected: (= (convert-amount {:amount-decimal-separator {:value \.}, :amount-grouping-separator {:value \_}} "9123_4567.89") "91,234,567.89")
  actual: (not (= "91.234.567,89" "91,234,567.89"))

lein test :only banks2ledger.core-test/test-convert-amount

FAIL in (test-convert-amount) (core_test.clj:259)
convert-amount
A number with a currency prefix and standard separators
expected: (= (convert-amount {:amount-decimal-separator {:value \.}, :amount-grouping-separator {:value \,}} "usd 10,123.45") "10,123.45")
  actual: (not (= "10.123,45" "10,123.45"))

lein test :only banks2ledger.core-test/test-convert-amount

FAIL in (test-convert-amount) (core_test.clj:263)
convert-amount
A number with custom spacing for groups
expected: (= (convert-amount {:amount-decimal-separator {:value \.}, :amount-grouping-separator {:value \,}} "-1234,5671.28") "-12,345,671.28")
  actual: (not (= "-12.345.671,28" "-12,345,671.28"))

lein test :only banks2ledger.core-test/test-amount-value

FAIL in (test-amount-value) (core_test.clj:197)
amount-value
expected: (= (amount-value "-10.24") -10.24)
  actual: (not (= -1024.0 -10.24))

lein test :only banks2ledger.core-test/test-amount-value

FAIL in (test-amount-value) (core_test.clj:198)
amount-value
expected: (= (amount-value "1,234.56") 1234.56)
  actual: (not (= 1.234 1234.56))

lein test :only banks2ledger.core-test/test-amount-value

FAIL in (test-amount-value) (core_test.clj:199)
amount-value
expected: (= (amount-value "1,234,567.89") 1234567.89)
  actual: (not (= 1.234 1234567.89))

Ran 23 tests containing 91 assertions.
23 failures, 0 errors.
Tests failed.
```

**Comment by tomszilagyi** [comment]
You have some locale setting in your shell that messes up things. The JVM
that runs Clojure picks up settings from there. For the record I have LANG
unset, LC_* unset, with the exception of LC_CTYPE=UTF-8 in my iTerm on
MacOS X 10.12.6 and it works fine (all the tests pass).

You could try something like `export LANG=en_US.UTF-8` before you run the
tests and see if that works. Then you can try to narrow it down to
something more specific (I think LC_NUMERIC is the one you actually need).
If that does not work for some reason, try `export LC_ALL=C` instead.

For reference look at LANG and LC_* here:
http://pubs.opengroup.org/onlinepubs/7908799/xbd/envvar.html

>

**Comment by qwerbzuio** [comment]
Thank you for your response. I tried various locale settings, including your suggestions, but couldn't fix the issue with any combination. I tried `export`ing these (... fishing in troubled waters):

```
- LC_ALL=C, LANG=C, LC_CTYPE unset
- LC_ALL=C, LANG=C, LC_CTYPE=UTF-8
- LC_ALL=C, LANG=en_US.UTF-8, LC_CTYPE unset
- LC_ALL=C, LANG=en_US.UTF-8, LC_CTYPE=UTF-8
- LC_ALL=en_US.UTF-8, LANG unset, LC_CTYPE=UTF-8
- LC_ALL=en_US.UTF-8, LANG=en_US.UTF-8, LC_CTYPE=UTF-8
- LC_ALL unset, LANG=en_US.UTF-8, LC_CTYPE=UTF-8
- LC_ALL unset, LANG unset, LC_CTYPE=UTF-8
- LC_ALL unset, LANG unset, LC_CTYPE unset
```

Could you think of any other settings to look at?

I am surprised that the locale settings may influence the thousands separator and decimal separator, as the program takes the parameters `-ds` and `-gs` for that purpose.

**Comment by tomszilagyi** [comment]
Considering that this simple formatting test fails:
```
FAIL in (test-format-value) (core_test.clj:189)
format-value
expected: (= (format-value 0.0) "0.00")
  actual: (not (= "0,00" "0.00"))
```

This has nothing to do with `-ds` and `gs` as those only set the number format for parsing your input, however the output format that is the result of printing numbers should be fixed.

I would argue that this problem is caused by a locale setting for your JVM, however that is picked up or configured. Maybe it is the global (OS level) language/country setting. I am not an expert on this (even less so on the Mac) but I would try to find a way to set the Java language/localisation settings. Cannot give you any specific advice unfortunately.

This might be a bug actually, in that the program should use an explicit format and not get "confused" by whatever locale settings are present. Will look into this some more later when I have more time, but it would be good if I could reproduce the problem (I suppose by setting the Mac and/or Java to some foreign locale). Out of curiosity, what locale settings do you have on your Mac?

**Comment by TwoD** [comment]
I can confirm this happens on my system as well. (Arch Linux)
With `env LANG=sv_SE.UTF-8 ./test.sh` (my default) all tests fail, and `ledger` won't be able to parse any large values as they are in the Swedish format `# ###,##`.
With `env LANG=en_US.UTF-8 ./test.sh` all tests pass because it's now using``#,###.##`.
I do not have any `LC_*' set in my environment.

Interestingly; `env LANG=foo ./test.sh` or even `env LC_MONETARY=foo LANG=bar ./test.sh` always pass, no matter what `foo/bar` is. Same if I override just `LC_MONETARY` and leave `LANG=sv_SE.UTF-8`.

(Running `banks2ledger` manually indicates the US format `#,###.##` is always used if `LC_MONETARY` - if set - and/or `LANG` can not be parsed.)

**Comment by dmos62** [comment]
On Windows 10 with Cygwin, I managed to somewhat fix this, or at least make it usable, by passing locale options to JVM:

`env JAVA_OPTS="-Duser.country=US -Duser.language=en" java -jar [...]`

Windows Java installation seems to ignore all the LANG, LC_MONETARY, etc. environment variables, or at least when they're passed from within Cygwin.

One problem persists, where ledger output of banks2ledger sometimes uses Windows line endings.  Sometimes, as in not on each line ending. If I don't replace all Windows line endings, banks2ledger can't read its own output. This is caught by the test suite:

```
$ env JAVA_OPTS="-Duser.country=US -Duser.language=en" lein test

lein test banks2ledger.core

lein test banks2ledger.core-test

lein test :only banks2ledger.core-test/test-print-ledger-entry

FAIL in (test-print-ledger-entry) (core_test.clj:316)
print-ledger-entry
expected: (= (with-out-str (print-ledger-entry {:date "2018-07-21", :descr "Custom Shop Extra", :verifs [{:comment "This is a comment"} {:account "Expenses:Random", :amount "123.45", :currency "SEK"} {:account "Assets:Pocket"}]})) (str "2018-07-21 Custom Shop Extra\n" "    ; This is a comment\n" "    Expenses:Random                       SEK 123.45\n" "    Assets:Pocket\n\n"))
  actual: (not (= "2018-07-21 Custom Shop Extra\r\n    ; This is a comment\n    Expenses:Random                       SEK 123.45\n    Assets:Pocket\n\r\n" "2018-07-21 Custom Shop Extra\n    ; This is a comment\n    Expenses:Random                       SEK 123.45\n    Assets:Pocket\n\n"))

lein test :only banks2ledger.core-test/test-print-ledger-entry

FAIL in (test-print-ledger-entry) (core_test.clj:329)
print-ledger-entry
expected: (= (with-out-str (print-ledger-entry {:date "2018-07-21", :ref "1234567890", :descr "Custom Shop Extra", :verifs [{:comment "This is a comment"} {:account "Expenses:Random", :amount "123.45", :currency "SEK"} {:account "Assets:Pocket"}]})) (str "2018-07-21 (1234567890) Custom Shop Extra\n" "    ; This is a comment\n" "    Expenses:Random                       SEK 123.45\n" "    Assets:Pocket\n\n"))
  actual: (not (= "2018-07-21 (1234567890) Custom Shop Extra\r\n    ; This is a comment\n    Expenses:Random                       SEK 123.45\n    Assets:Pocket\n\r\n" "2018-07-21 (1234567890) Custom Shop Extra\n    ; This is a comment\n    Expenses:Random                       SEK 123.45\n    Assets:Pocket\n\n"))

lein test :only banks2ledger.core-test/test-print-ledger-entry-via-hook-formatters

FAIL in (test-print-ledger-entry-via-hook-formatters) (core_test.clj:403)
print-ledger-entry-via-hook-formatters
expected: (= (with-out-str (simple-salary-hook-formatter {:date "2017/07/25", :descr "LÖN", :ref "TXN123456789", :account "Assets:Bank:Account", :amount "29,290.00", :currency "SEK"})) (str "2017/07/25 (TXN123456789) LÖN\n" "    ; Pay stub data\n" "    Tax:2017:GrossIncome                  SEK -00,000.00\n" "    Tax:2017:IncomeTax                    SEK 0,000.00\n" "    Tax:2017:NetIncome\n" "    ; Distribution of net income\n" "    Assets:Bank:Account                   SEK 29,290.00\n" "    Income:Salary                         SEK -29,290.00\n\n"))
  actual: (not (= "2017/07/25 (TXN123456789) LÖN\r\n    ; Pay stub data\n    Tax:2017:GrossIncome                  SEK -00,000.00\n    Tax:2017:IncomeTax                    SEK 0,000.00\n    Tax:2017:NetIncome\n    ; Distribution of net income\n    Assets:Bank:Account                   SEK 29,290.00\n    Income:Salary                         SEK -29,290.00\n\r\n" "2017/07/25 (TXN123456789) LÖN\n    ; Pay stub data\n    Tax:2017:GrossIncome                  SEK -00,000.00\n    Tax:2017:IncomeTax                    SEK 0,000.00\n    Tax:2017:NetIncome\n    ; Distribution of net income\n    Assets:Bank:Account                   SEK 29,290.00\n    Income:Salary                         SEK -29,290.00\n\n"))

lein test :only banks2ledger.core-test/test-print-ledger-entry-via-hook-formatters

FAIL in (test-print-ledger-entry-via-hook-formatters) (core_test.clj:419)
print-ledger-entry-via-hook-formatters
expected: (= (with-out-str (advanced-salary-hook-formatter {:date "2018/07/25", :descr "LÖN", :ref "TXN123456789", :account "Assets:Bank:Account", :amount "27,365.00", :currency "SEK"})) (str "2018/07/25 (TXN123456789) LÖN\n" "    ; Pay stub data\n" "    Tax:2018:GrossIncome                  SEK -38,500.00\n" "    Tax:2018:IncomeTax                    SEK 9,210.00\n" "    Tax:2018:NetIncome\n" "    ; Distribution of net income\n" "    Income:Salary                         SEK -29,290.00\n" "    Equity:SPP:Collect                    SEK 1,925.00\n" "    Assets:Bank:Account                   SEK 27,365.00\n\n"))
  actual: (not (= "2018/07/25 (TXN123456789) LÖN\r\n    ; Pay stub data\n    Tax:2018:GrossIncome                  SEK -38,500.00\n    Tax:2018:IncomeTax                    SEK 9,210.00\n    Tax:2018:NetIncome\n    ; Distribution of net income\n    Income:Salary                         SEK -29,290.00\n    Equity:SPP:Collect                    SEK 1,925.00\n    Assets:Bank:Account                   SEK 27,365.00\n\r\n" "2018/07/25 (TXN123456789) LÖN\n    ; Pay stub data\n    Tax:2018:GrossIncome                  SEK -38,500.00\n    Tax:2018:IncomeTax                    SEK 9,210.00\n    Tax:2018:NetIncome\n    ; Distribution of net income\n    Income:Salary                         SEK -29,290.00\n    Equity:SPP:Collect                    SEK 1,925.00\n    Assets:Bank:Account                   SEK 27,365.00\n\n"))

Ran 23 tests containing 91 assertions.
4 failures, 0 errors.
Tests failed.

```

I tried adding this to JAVA_OPTS to get the tests to pass, but no luck:

```
-Dline.separator=$'\r'
```

**Comment by qwerbzuio** [comment]
Same on my MacOS 10.12. Thanks for the fix.
